In [1]:
pwd

u'/Users/2015/Dropbox/Data Science/NYC Data Science Academy/class-projects/Capstone'

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data/SF1_retail.csv")

In [9]:
df.head()

,Ticker,Date,ACCOCI_ARQ,ACCOCI_MRQ,ASSETSAVG_ART,ASSETSAVG_MRT,ASSETSC_ARQ,ASSETSC_MRQ,ASSETSNC_ARQ,ASSETSNC_MRQ,...,TAXEXP_ARQ,TAXEXP_ART,TAXEXP_ARY,TAXEXP_MRQ,TAXEXP_MRT,TAXEXP_MRY,TBVPS_ARQ,TBVPS_MRQ,WORKINGCAPITAL_ARQ,WORKINGCAPITAL_MRQ
0,AAN,2004-03-15,0,NaN,516004250,NaN,NaN,NaN,NaN,NaN,...,6031000,21417000,21417000,NaN,NaN,NaN,6.780101,NaN,NaN,NaN
1,AAN,2004-03-31,NaN,2317000,NaN,540260500,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,7889000,24147000,NaN,NaN,7.112449,NaN,NaN
2,AAN,2004-05-07,2317000,NaN,539112500,NaN,NaN,NaN,NaN,NaN,...,7889000,24147000,NaN,NaN,NaN,NaN,7.112449,NaN,NaN,NaN
3,AAN,2004-06-30,NaN,-588000,NaN,568324500,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9543000,28545000,NaN,NaN,7.309370,NaN,NaN
4,AAN,2004-08-06,-588000,NaN,567176500,NaN,NaN,NaN,NaN,NaN,...,9543000,28545000,NaN,NaN,NaN,NaN,7.309370,NaN,NaN,NaN

In [14]:
companies = pd.read_csv("data/companies.csv")

In [15]:
companies

                                     Company Ticker
0                      1-800-Flowers.Com Inc   FLWS
1                       99 Cents Only Stores    NDN
2                              Aaron's, Inc.    AAN
3                    Abercrombie & Fitch Co.    ANF
4                   Advance Auto Parts, Inc.    AAP
5                           Amazon.com, Inc.   AMZN
6                  American Eagle Outfitters    AEO
7                                    Ann Inc    ANN
8              Asbury Automotive Group, Inc.    ABG
9                    Ascena Retail Group Inc   ASNA
10                          AutoNation, Inc.     AN
11                            AutoZone, Inc.    AZO
12              Barnes & Noble Education Inc   BNED
13                      Barnes & Noble, Inc.    BKS
14                    Bed Bath & Beyond Inc.   BBBY
15                           Best Buy Co Inc    BBY
16                            Big Lots, Inc.    BIG
17                             Blue Nile Inc   NILE
18                                Buckle Inc    BKE
19                     Burlington Stores Inc   BURL
20                               Cabelas Inc    CAB
21                               CarMax, Inc    KMX
22                            Carter's, Inc.    CRI
23                                 Cato Corp   CATO
24                         Chico's FAS, Inc.    CHS
25                       Childrens Place Inc   PLCE
26                                 Coach Inc    COH
27                              CONN'S, Inc.   CONN
28                 Container Store Group Inc    TCS
29                              Copart, Inc.   CPRT
..                                       ...    ...
86                            PetSmart, Inc.   PETM
87                        Pier 1 Imports Inc    PIR
88                          PriceSmart, Inc.   PSMT
89                                       QVC   QVCA
90                         Rent-A-Center Inc   RCII
91         Restoration Hardware Holdings Inc     RH
92                         Ross Stores, Inc.   ROST
93                    Rush Enterprises, Inc.  RUSHA
94               Sally Beauty Holdings, Inc.    SBH
95                       Sears Holdings Corp   SHLD
96                       Shoe Carnival, Inc.   SCVL
97                      Signet Jewelers Ltd.    SIG
98                      Sonic Automotive Inc    SAH
99        Sportsman's Warehouse Holdings Inc   SPWH
100                          Stamps.com Inc.   STMP
101                            Staples, Inc.   SPLS
102                       Target Corporation    TGT
103                           Tech Data Corp   TECD
104                            Tiffany & Co.    TIF
105                        TJX Companies Inc    TJX
106                   Tractor Supply Company   TSCO
107  Ulta Salon, Cosmetics & Fragrance, Inc.   ULTA
108                   Urban Outfitters, Inc.   URBN
109               Vipshop Holdings Ltd - ADR   VIPS
110                       Vitamin Shoppe Inc    VSI
111                    Wal-Mart Stores, Inc.    WMT
112                              Wayfair Inc      W
113                    Williams-Sonoma, Inc.    WSM
114                      Winmark Corporation   WINA
115                              Zumiez Inc.   ZUMZ

[116 rows x 2 columns]

In [23]:
retail =pd.merge(companies, df, on='Ticker', how = 'outer')

In [24]:
retail.head()

,Company,Ticker,Date,ACCOCI_ARQ,ACCOCI_MRQ,ASSETSAVG_ART,ASSETSAVG_MRT,ASSETSC_ARQ,ASSETSC_MRQ,ASSETSNC_ARQ,...,TAXEXP_ARQ,TAXEXP_ART,TAXEXP_ARY,TAXEXP_MRQ,TAXEXP_MRT,TAXEXP_MRY,TBVPS_ARQ,TBVPS_MRQ,WORKINGCAPITAL_ARQ,WORKINGCAPITAL_MRQ
0,1-800-Flowers.Com Inc,FLWS,2008-06-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,13126000,13126000,NaN,NaN,NaN,NaN
1,1-800-Flowers.Com Inc,FLWS,2008-09-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-2017000,NaN,NaN,NaN,NaN,NaN,NaN
2,1-800-Flowers.Com Inc,FLWS,2009-03-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-17569000,NaN,NaN,NaN,NaN,NaN,NaN
3,1-800-Flowers.Com Inc,FLWS,2009-06-28,NaN,0,NaN,NaN,NaN,122097000,NaN,...,NaN,NaN,NaN,-4713000,-15326000,-15326000,NaN,3.184839,NaN,43667000
4,1-800-Flowers.Com Inc,FLWS,2009-09-27,NaN,-279000,NaN,NaN,NaN,138702000,NaN,...,NaN,NaN,NaN,-3622000,NaN,NaN,NaN,3.419240,NaN,33558000

In [28]:
indicators = retail.columns.tolist()

In [36]:
# 8 rows have Dates which are missing
retail.sort_values("Date", na_position='first')

,Company,Ticker,Date,ACCOCI_ARQ,ACCOCI_MRQ,ASSETSAVG_ART,ASSETSAVG_MRT,ASSETSC_ARQ,ASSETSC_MRQ,ASSETSNC_ARQ,...,TAXEXP_ARQ,TAXEXP_ART,TAXEXP_ARY,TAXEXP_MRQ,TAXEXP_MRT,TAXEXP_MRY,TBVPS_ARQ,TBVPS_MRQ,WORKINGCAPITAL_ARQ,WORKINGCAPITAL_MRQ
1181,Barnes & Noble Education Inc,BNED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3645,Etsy,ETSY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5272,Hudson's Bay,HBC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6073,Liberty Ventures,LVNTA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6386,Luxottica Group SpA (ADR),LUX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7153,Ollie's Bargain Outlet Holdings Inc,OLLI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7262,Party City Holdco Inc,PRTY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9557,Vipshop Holdings Ltd - ADR,VIPS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1407,Best Buy Co Inc,BBY,2003-01-14,1000000,NaN,NaN,NaN,6053000000,NaN,2.808000e+09,...,53000000,NaN,NaN,NaN,NaN,NaN,17.463971,NaN,768000000,NaN
9435,"Urban Outfitters, Inc.",URBN,2003-01-31,NaN,692000,NaN,263696000,NaN,145765000,NaN,...,NaN,NaN,NaN,5703000,18660000,18660000,NaN,1.783871,NaN,101512000
8979,Tech Data Corp,TECD,2003-01-31,NaN,40327000,NaN,3353174000,NaN,2978118000,NaN,...,NaN,NaN,NaN,16325000,67128000,67128000,NaN,57.459973,NaN,1399283000
9612,"Wal-Mart Stores, Inc.",WMT,2003-01-31,NaN,-509000000,NaN,89167500000,NaN,30722000000,NaN,...,NaN,NaN,NaN,1369000000,4357000000,4357000000,NaN,19.373781,NaN,-1797000000
6171,"Lowe's Companies, Inc.",LOW,2003-01-31,NaN,1000000,NaN,15739500000,NaN,5568000000,NaN,...,NaN,NaN,NaN,205000000,893000000,893000000,NaN,NaN,NaN,1990000000
8345,"Shoe Carnival, Inc.",SCVL,2003-02-01,NaN,0,NaN,NaN,NaN,155798000,NaN,...,NaN,NaN,NaN,898000,9400000,9400000,NaN,11.593571,NaN,96248000
2420,Childrens Place Inc,PLCE,2003-02-01,NaN,253000,NaN,NaN,NaN,145203000,NaN,...,NaN,NaN,NaN,NaN,5861000,5861000,NaN,11.672314,NaN,79274000
562,American Eagle Outfitters,AEO,2003-02-01,NaN,0,NaN,717187250,NaN,426726000,NaN,...,NaN,NaN,NaN,30825000,61635000,61635000,NaN,3.363301,NaN,285140000
1182,"Barnes & Noble, Inc.",BKS,2003-02-01,NaN,-11064000,NaN,2941190250,NaN,1886868000,NaN,...,NaN,NaN,NaN,47020000,44609000,44609000,NaN,39.593896,NaN,655420000
4952,"Hibbett Sports, Inc.",HIBB,2003-02-01,NaN,0,NaN,122447500,NaN,103191000,NaN,...,NaN,NaN,NaN,NaN,8182000,8182000,NaN,3.825884,NaN,70961000
5647,Kohl's Corporation,KSS,2003-02-01,NaN,0,NaN,5690416500,NaN,3284289000,NaN,...,NaN,NaN,NaN,164714000,386187000,386187000,NaN,NaN,NaN,1776102000
7359,Pep Boys-Manny Moe and Jack,PBY,2003-02-01,NaN,-151000,NaN,NaN,NaN,664870000,NaN,...,NaN,NaN,NaN,NaN,22782000,22782000,NaN,NaN,NaN,130680000
5774,L Brands Inc,LB,2003-02-01,NaN,0,NaN,NaN,NaN,3606000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2347000000
4362,Gap Inc,GPS,2003-02-01,NaN,-16000000,NaN,9504012250,NaN,5740000000,NaN,...,NaN,NaN,NaN,120166000,323000000,323000000,NaN,11.167226,NaN,3014000000
1408,Best Buy Co Inc,BBY,2003-03-01,NaN,0,NaN,7505000000,NaN,4898000000,NaN,...,NaN,NaN,NaN,239000000,392000000,392000000,NaN,14.987048,NaN,1074000000
5648,Kohl's Corporation,KSS,2003-03-21,0,NaN,NaN,NaN,3284094000,NaN,3.031409e+09,...,NaN,390993000,390993000,NaN,NaN,NaN,18.692921,NaN,1776102000,NaN
4736,"Guess?, Inc.",GES,2003-03-27,-1565000,NaN,NaN,NaN,188987000,NaN,1.605450e+08,...,NaN,-5550000,-5550000,NaN,NaN,NaN,4.027609,NaN,21426000,NaN
4737,"Guess?, Inc.",GES,2003-03-29,NaN,-889000,NaN,NaN,NaN,178533000,NaN,...,NaN,NaN,NaN,-4350000,-7100000,NaN,NaN,3.755772,NaN,87459000
4363,Gap Inc,GPS,2003-04-01,-16766000,NaN,NaN,NaN,5739725000,NaN,4.162279e+09,...,NaN,323418000,323418000,NaN,NaN,NaN,11.309525,NaN,3013151000,NaN
563,American Eagle Outfitters,AEO,2003-04-02,0,NaN,NaN,NaN,427878000,NaN,3.134610e+08,...,NaN,54878000,54878000,NaN,NaN,NaN,3.336285,NaN,286292000,NaN
3144,"Dillard's, Inc.",DDS,2003-04-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9613,"Wal-Mart Stores, Inc.",WMT,2003-04-15,-509000000,NaN,NaN,NaN,30483000000,NaN,6.420200e+10,...,NaN,4487000000,4487000000,NaN,NaN,NaN,19.224379,NaN,-2134000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9254,TJX Companies Inc,TJX,2015-12-01,-545175000,NaN,1.145695e+10,NaN,7348157000,NaN,4.644276e+09,...,353934000,1362712000,NaN,NaN,NaN,NaN,17.228676,NaN,2618079000,NaN
6302,"Lowe's Companies, Inc.",LOW,2015-12-02,-379000000,NaN,3.316225e+10,NaN,12395000000,NaN,2.126000e+10,...,451000000,1826000000,NaN,NaN,NaN,NaN,36.661220,NaN,233000000,NaN
3525,DSW Inc.,DSW,2015-12-02,-13531000,NaN,1.483074e+09,NaN,677100000,NaN,7.809280e+08,...,25575000,96684000,NaN,NaN,NaN,NaN,16.535354,NaN,390039000,NaN
4858,"Guess?, Inc.",GES,2015-12-02,-142239000,NaN,1.560682e+09,NaN,1050145000,NaN,4.723270e+08,...,8005000,46133000,NaN,NaN,NaN,NaN,17.632518,NaN,723095000,NaN
9739,"Wal-Mart Stores, Inc.",WMT,2015-12-02,-10659000000,NaN,2.020542e+11,NaN,65112000000,NaN,1.400320e+11,...,1748000000,7387000000,NaN,NaN,NaN,NaN,58.595950,NaN,-5380000000,NaN
8344,Sears Holdings Corp,SHLD,2015-12-03,0,NaN,1.311350e+10,NaN,7219000000,NaN,5.550000e+09,...,14000000,-252000000,NaN,NaN,NaN,NaN,97.654784,NaN,701000000,NaN
5922,"Lands' End, Inc.",LE,2015-12-03,-6373000,NaN,1.363581e+09,NaN,625060000,NaN,7.642960e+08,...,5572000,33144000,NaN,NaN,NaN,NaN,23.477103,NaN,363509000,NaN
3322,Dollar General Corp.,DG,2015-12-03,-6013000,NaN,1.116604e+10,NaN,3488775000,NaN,7.799518e+09,...,148818000,664778000,NaN,NaN,NaN,NaN,19.684471,NaN,1497192000,NaN
9080,Tech Data Corp,TECD,2015-12-03,28534000,NaN,6.138714e+09,NaN,5802434000,NaN,5.626330e+08,...,19636000,91543000,NaN,NaN,NaN,NaN,180.753876,NaN,1835318000,NaN
9434,"Ulta Salon, Cosmetics & Fragrance, Inc.",ULTA,2015-12-03,0,NaN,2.104257e+09,NaN,1388190000,NaN,8.518080e+08,...,39982000,175930000,NaN,NaN,NaN,NaN,35.064619,NaN,930214000,NaN
686,American Eagle Outfitters,AEO,2015-12-04,-19797000,NaN,1.754428e+09,NaN,1050347000,NaN,8.374890e+08,...,40367000,120601000,NaN,NaN,NaN,NaN,9.364557,NaN,472204000,NaN
3245,"Dillard's, Inc.",DDS,2015-12-04,-29314000,NaN,4.256386e+09,NaN,2150871000,NaN,2.229315e+09,...,24970000,168180000,NaN,NaN,NaN,NaN,119.302811,NaN,820067000,NaN
5901,L Brands Inc,LB,2015-12-04,41000000,NaN,7.238750e+09,NaN,3564000000,NaN,4.405000e+09,...,96000000,651000000,NaN,NaN,NaN,NaN,21.559290,NaN,1836000000,NaN
1304,"Barnes & Noble, Inc.",BKS,2015-12-04,-16533000,NaN,3.301816e+09,NaN,1582005000,NaN,8.657210e+08,...,-30694000,24232000,NaN,NaN,NaN,NaN,25.378072,NaN,195751000,NaN
3953,Five Below Inc,FIVE,2015-12-04,0,NaN,3.336422e+08,NaN,275839000,NaN,1.215460e+08,...,2683000,29187000,NaN,NaN,NaN,NaN,7.287536,NaN,124791000,NaN
6699,Michaels Companies Inc,MIK,2015-12-04,-14624000,NaN,1.968711e+09,NaN,1544885000,NaN,5.382540e+08,...,45103000,194960000,NaN,NaN,NaN,NaN,9.592997,NaN,585859000,NaN
8534,Signet Jewelers Ltd.,SIG,2015-12-04,-245800000,NaN,6.313425e+09,NaN,4482500000,NaN,1.987200e+09,...,6900000,176600000,NaN,NaN,NaN,NaN,69.581337,NaN,3040700000,NaN
5773,Kohl's Corporation,KSS,2015-12-04,-18000000,NaN,1.456175e+10,NaN,6203000000,NaN,8.695000e+09,...,69000000,417000000,NaN,NaN,NaN,NaN,78.484781,NaN,2264000000,NaN
1537,Best Buy Co Inc,BBY,2015-12-04,296000000,NaN,1.442900e+10,NaN,11735000000,NaN,3.440000e+09,...,84000000,504000000,NaN,NaN,NaN,NaN,42.738613,NaN,3340000000,NaN
341,Abercrombie & Fitch Co.,ANF,2015-12-07,-106230000,NaN,2.451176e+09,NaN,1213155000,NaN,1.299589e+09,...,-5881000,2314000,NaN,NaN,NaN,NaN,36.487439,NaN,568745000,NaN
7471,Pep Boys-Manny Moe and Jack,PBY,2015-12-08,-519000,NaN,1.515501e+09,NaN,797481000,NaN,6.948740e+08,...,476000,6012000,NaN,NaN,NaN,NaN,26.958115,NaN,183663000,NaN
4489,Gap Inc,GPS,2015-12-08,105000000,NaN,7.569500e+09,NaN,4361000000,NaN,3.445000e+09,...,148000000,608000000,NaN,NaN,NaN,NaN,19.226601,NaN,1593000000,NaN
6544,Mattress Firm Holding Corp,MFRM,2015-12-08,0,NaN,1.637597e+09,NaN,286934000,NaN,1.371785e+09,...,13778000,36029000,NaN,NaN,NaN,NaN,17.610907,NaN,-11441000,NaN
4361,GameStop Corp.,GME,2015-12-08,-61300000,NaN,4.216675e+09,NaN,2494400000,NaN,2.340600e+09,...,28300000,230400000,NaN,NaN,NaN,NaN,29.074004,NaN,122700000,NaN
8459,"Shoe Carnival, Inc.",SCVL,2015-12-08,0,NaN,4.899708e+08,NaN,377425000,NaN,1.123770e+08,...,5747000,16966000,NaN,NaN,NaN,NaN,25.190393,NaN,284290000,NaN
2723,"CONN'S, Inc.",CONN,2015-12-08,0,NaN,1.775227e+09,NaN,1277630000,NaN,8.112130e+08,...,-732000,25091000,NaN,NaN,NaN,NaN,58.504453,NaN,1073991000,NaN
2534,Childrens Place Inc,PLCE,2015-12-08,-20243000,NaN,9.520082e+08,NaN,634454000,NaN,3.429040e+08,...,18898000,23263000,NaN,NaN,NaN,NaN,48.152830,NaN,300750000,NaN
9556,"Urban Outfitters, Inc.",URBN,2015-12-08,-12651000,NaN,1.897491e+09,NaN,847226000,NaN,1.029309e+09,...,28394000,126174000,NaN,NaN,NaN,NaN,15.201640,NaN,469339000,NaN
5073,"Hibbett Sports, Inc.",HIBB,2015-12-08,0,NaN,4.607690e+08,NaN,352073000,NaN,9.989900e+07,...,11115000,43011000,NaN,NaN,NaN,NaN,19.145677,NaN,222146000,NaN
10079,Zumiez Inc.,ZUMZ,2015-12-08,-13920000,NaN,4.744192e+08,NaN,220680000,NaN,2.203900e+08,...,5584000,22539000,NaN,NaN,NaN,NaN,14.151207,NaN,131514000,NaN

In [40]:
# delete rows where "Date" = NaN
retail = retail[retail.Date.notnull()]

In [43]:
# confirmn that 8 rows were deleted
retail.shape

(10072, 297)

In [44]:
retail.sort_values("Date").head()

,Company,Ticker,Date,ACCOCI_ARQ,ACCOCI_MRQ,ASSETSAVG_ART,ASSETSAVG_MRT,ASSETSC_ARQ,ASSETSC_MRQ,ASSETSNC_ARQ,...,TAXEXP_ARQ,TAXEXP_ART,TAXEXP_ARY,TAXEXP_MRQ,TAXEXP_MRT,TAXEXP_MRY,TBVPS_ARQ,TBVPS_MRQ,WORKINGCAPITAL_ARQ,WORKINGCAPITAL_MRQ
1407,Best Buy Co Inc,BBY,2003-01-14,1000000,NaN,NaN,NaN,6053000000,NaN,2808000000,...,53000000,NaN,NaN,NaN,NaN,NaN,17.463971,NaN,768000000,NaN
9435,"Urban Outfitters, Inc.",URBN,2003-01-31,NaN,692000,NaN,263696000,NaN,145765000,NaN,...,NaN,NaN,NaN,5703000,18660000,18660000,NaN,1.783871,NaN,101512000
8979,Tech Data Corp,TECD,2003-01-31,NaN,40327000,NaN,3353174000,NaN,2978118000,NaN,...,NaN,NaN,NaN,16325000,67128000,67128000,NaN,57.459973,NaN,1399283000
9612,"Wal-Mart Stores, Inc.",WMT,2003-01-31,NaN,-509000000,NaN,89167500000,NaN,30722000000,NaN,...,NaN,NaN,NaN,1369000000,4357000000,4357000000,NaN,19.373781,NaN,-1797000000
6171,"Lowe's Companies, Inc.",LOW,2003-01-31,NaN,1000000,NaN,15739500000,NaN,5568000000,NaN,...,NaN,NaN,NaN,205000000,893000000,893000000,NaN,NaN,NaN,1990000000

### Dates start at 2003